<a href="https://colab.research.google.com/github/OlyMahmudMugdho/deep-learning/blob/main/1-basic-nn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [214]:
import torch
import torch.nn as nn

In [215]:
model = nn.Sequential(
    nn.Linear(4, 8),
    nn.Linear(8,5),
    nn.Linear(5, 3),
    nn.Linear(3,2),
    nn.Sigmoid()
)

In [216]:
input = torch.Tensor([[4,9,2,7]])

In [217]:
output = model(input)
print(output)

tensor([[0.5508, 0.4305]], grad_fn=<SigmoidBackward0>)


In [218]:
target = torch.tensor([0], dtype=torch.long)

In [219]:
criterion = nn.CrossEntropyLoss()

In [220]:
loss = criterion(output, target)
print(loss)

tensor(0.6348, grad_fn=<NllLossBackward0>)


In [221]:
loss.backward()

In [222]:
weight = model[0].weight
print(weight)

Parameter containing:
tensor([[ 1.1029e-01,  1.7856e-01,  1.3982e-01,  4.7555e-01],
        [-4.8498e-01, -4.1389e-01, -1.2574e-01, -2.4140e-01],
        [ 1.4012e-01,  1.5405e-01,  4.0797e-01,  6.7955e-02],
        [-6.4981e-02,  2.7438e-01,  1.3389e-01,  1.2237e-01],
        [ 5.7573e-02,  2.7562e-01,  1.2220e-01, -1.5634e-01],
        [ 4.3388e-01, -4.8999e-01, -3.4951e-01,  1.8209e-04],
        [-9.6830e-02, -1.6546e-01, -3.6889e-01,  8.5254e-02],
        [-1.5704e-01,  1.9875e-02, -2.5027e-01, -1.3152e-01]],
       requires_grad=True)


In [223]:
weight_grad = weight.grad
print(weight_grad)

tensor([[ 0.0094,  0.0212,  0.0047,  0.0165],
        [ 0.0095,  0.0215,  0.0048,  0.0167],
        [-0.0394, -0.0887, -0.0197, -0.0690],
        [ 0.0626,  0.1410,  0.0313,  0.1096],
        [-0.0310, -0.0698, -0.0155, -0.0543],
        [ 0.0336,  0.0757,  0.0168,  0.0589],
        [-0.0058, -0.0131, -0.0029, -0.0102],
        [-0.0270, -0.0608, -0.0135, -0.0473]])


In [224]:
bias = model[0].bias
print(bias)

Parameter containing:
tensor([ 0.1035, -0.2401,  0.1706,  0.0092, -0.4658, -0.1869, -0.3205,  0.4932],
       requires_grad=True)


In [225]:
bias_grad = bias.grad
print(bias_grad)

tensor([ 0.0024,  0.0024, -0.0099,  0.0157, -0.0078,  0.0084, -0.0015, -0.0068])


In [226]:
learning_rate = 0.01

In [227]:
with torch.no_grad():
    model[0].weight.copy_(model[0].weight - learning_rate * model[0].weight.grad)
    model[0].bias.copy_(model[0].bias - learning_rate * model[0].bias.grad)

print("Model parameters updated in-place.")

Model parameters updated in-place.


In [228]:
output = model(input)
print("New Output:", output)
loss = criterion(output, target)
print("New Loss:", loss)

New Output: tensor([[0.5514, 0.4295]], grad_fn=<SigmoidBackward0>)
New Loss: tensor(0.6340, grad_fn=<NllLossBackward0>)
